### ISSUE TITLE
SVN Integration

### ISSUE THREAD

**Issue by korut94** [BugBusterSWE/Chronos#3]
SVN give a vantage: the partial download. This improve perfomance when we download only module from plugin.

**Comment by Polpetta** [comment]
Yeah this could be a good idea.
We can also support Mercurial.
What di you think?
Il 10 feb 2016 20:49, "Andrea Mantovani" notifications@github.com ha
scritto:

**Comment by korut94** [comment]
In the next versions maybe. At the moment, git is strongly integrate with the system and only including svn will be more difficult.

**Comment by Polpetta** [comment]
Ok. It isn't a problem.
